#include <Arduino.h>
#include <SPI.h>
#include <DMD2TUR.h>
#include "Arial14.h"
#include "Arial_Black_16.h"
#include "Droid_Sans_12.h"
#include "Droid_Sans_16.h"
#include "Droid_Sans_24.h"
#include "SystemFont5x7TR.h"
#include "SystemFont5x11Tr.h"